#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CSV（grid_summary_*.csv）から LaTeX（longtable）を自動生成するスクリプト。
VS Code等の実行ボタンでそのまま走らせられるように、設定値をコード上部にまとめました。

機能:
- N=4..8 全生成
- 手法の並び順を「分類表の順」に固定
- 不要な設定項目を削除しシンプル化
- 出力したい指標（カラム）や基準をリストで自由に定義可能
"""

from __future__ import annotations

import os
import warnings
from pathlib import Path
from typing import Dict, List, Tuple

import pandas as pd

# -----------------------------------------------------------------------------
# 警告の抑制（PandasのFutureWarning対策）
# -----------------------------------------------------------------------------
warnings.simplefilter(action='ignore', category=FutureWarning)


# =============================================================================
# 【基本設定】 ファイルパスや出力モード
# =============================================================================

# 入力CSVファイルのパス
INPUT_CSV_PATH = "tex_data/grid_summary_maximinmaximax_v5.csv"

# 出力先フォルダ名
OUTPUT_DIR = "tex_data/generated_tables_all"

# 生成対象のN (リスト形式で指定)
TARGET_NS = [4, 5, 6, 7, 8]

# 1ページに1つの表を強制するかどうか
ONE_TABLE_PER_PAGE = False


# =============================================================================
# 【出力対象の定義】 ここを編集して、必要な指標・基準だけを選んでください
# =============================================================================

# 1. 評価指標のリスト
#    形式: (内部ID, CSVのカラム名, 日本語キャプション名)
#    ※ 不要な行は削除またはコメントアウトしてください
TARGET_METRICS = [
    ("recall",    "sum_recall",    "再現数平均"),
    ("precision", "sum_precision", "正解数平均"),
    ("f1",        "sum_f1",        "F1平均"),
]
# TARGET_METRICS = [
#     # (ファイル名の一部, CSVカラム名, TeXキャプション)
#     ("recall_worst",    "sum_recall_worst",    "再現数平均（最悪）"),
#     ("precision_worst", "sum_precision_worst", "正解数平均（最悪）"),
#     ("f1_worst",        "sum_f1_worst",        "F1平均（最悪）"),
# ]
# 2. 基準（Rule）のリスト
#    形式: (CSV内の値, 日本語キャプション名)
TARGET_RULES = [
    ("maximin",        "マキシミン基準"),
    ("maximax",        "マキシマックス基準"),
    ("minimax_regret", "ミニマックス・リグレット基準"),
]

# 3. 効用（Utility）のリスト
#    形式: (CSV内の値, 日本語キャプション名)
TARGET_UTILITIES = [
    ("u1", "効用値順序付け容易な場合"),
    ("u2", "効用値順序付け困難な場合"),
]


# =============================================================================
# 【分類表の設定】 手法の並び順やグループ定義
# =============================================================================
# CSVの実態に合わせて手法名を更新しました。
# グループ内の並び順を変更したい場合は、リスト内の順序を入れ替えてください。
METHOD_GROUPS: List[Tuple[str, List[str]]] = [
    ("クリスプ推定法", [
        "EV", "GM",
    ]),
    ("基本区間推定法（単一モデル）", [
        "WMIN", "WWMIN", "DMIN",
    ]),
    ("中心固定型（単一モデル）", [
        "E-WMIN", "E-WWMI", "E-DMIN",
        "G-WMIN", "G-WWMI", "G-DMIN",
    ]),
    ("アンサンブル型・区間包統合（MMR系）", [
        "MMRW", "MMRWW", "MMRD", "MMRwc",
        "E-MMRW", "E-MMRWW", "E-MMRD",
        "G-MMRW", "G-MMRWW", "G-MMRD",
    ]),
    ("アンサンブル型・平均統合（AMR系）", [
        "AMRW", "AMRWW", "AMRD", "AMRwc",
        "E-AMRW", "E-AMRWW", "E-AMRD",
        "G-AMRW", "G-AMRWW", "G-AMRD",
    ]),
    ("弱モデル内中心推定型・区間包統合", [
        "eMMRw", "eMMRwc", "eMMRd", "eMMRdc",
        "gMMRw", "gMMRwc", "gMMRd", "gMMRdc",
    ]),
    ("弱モデル内中心推定型・平均統合", [
        "eAMRw", "eAMRwc", "eAMRd", "eAMRdc",
        "gAMRw", "gAMRwc", "gAMRd", "gAMRdc",
    ]),
]

# -----------------------------------------------------------------------------
# 以下、ロジック部分
# -----------------------------------------------------------------------------

# 表の列（tw）順
TW_ORDER = ["A", "B", "C", "D", "E"]

# CSV列名定義
COL_RULE = "rule"
COL_N = "N"
COL_TW = "tw"
COL_UTILITY = "utility"
COL_METHOD = "method"
COL_CASES = "cases"


def flatten_method_order(groups: List[Tuple[str, List[str]]]) -> List[str]:
    order: List[str] = []
    for _, methods in groups:
        order.extend(methods)
    return order


def sanitize_method_tex(name: str) -> str:
    """TeX表示用"""
    return name


def format_value(v: float) -> str:
    """常に整数（カンマ区切り）でフォーマット"""
    if pd.isna(v):
        return "--"
    return f"{int(round(v)):,}"


def compute_cell_value(sum_val: float, cases: float) -> float:
    """常に合計値をそのまま返す（平均化しない）"""
    if pd.isna(sum_val) or pd.isna(cases) or cases == 0:
        return float("nan")
    return float(sum_val)


def write_table_style(out_dir: Path) -> None:
    style = r"""
% generated by script
\providecommand{\AppendixTableSetup}{}%
\renewcommand{\AppendixTableSetup}{%
  \footnotesize%
  \setlength{\tabcolsep}{5.0pt}%
  \renewcommand{\arraystretch}{0.92}%
  \setlength{\LTleft}{\fill}%
  \setlength{\LTright}{\fill}%
}
"""
    (out_dir / "table_style.tex").write_text(style.strip() + "\n", encoding="utf-8")


def build_longtable_tex(
    df: pd.DataFrame,
    rule_key: str,
    rule_label: str,
    N: int,
    util_key: str,
    util_label: str,
    metric_col: str,
    metric_label: str,
    method_order: List[str],
) -> str:
    """
    1つの longtable を生成
    """
    # caption
    caption = f"{metric_label} : {util_label}（{rule_label}，n = {N}）"

    # pivot
    sub = df[(df[COL_RULE] == rule_key) & (df[COL_N] == N) & (df[COL_UTILITY] == util_key)]
    
    if sub.empty:
        return rf"""\AppendixTableSetup
\begin{{longtable}}{{l|r}}
\caption{{{caption}}}\\
\hline
手法名 & 値 \\
\hline\hline
データ無し & -- \\
\hline
\end{{longtable}}
"""

    # 値計算（twごと）
    def agg_one(g: pd.DataFrame) -> float:
        # 指定された metric_col を集計
        if metric_col not in g.columns:
            return float("nan")
        s = g[metric_col].mean() # 同じ条件の行があれば平均をとる（通常1行）
        c = g[COL_CASES].mean()
        return compute_cell_value(s, c)

    val = (
        sub.groupby([COL_METHOD, COL_TW], dropna=False)
        .apply(agg_one)
        .reset_index(name="val")
    )

    # Total列
    total = (
        val.groupby(COL_METHOD)["val"].mean().reset_index(name="total")
    )

    # method order & slice (skipなしで常に全件対象)
    ordered_methods = [m for m in method_order if m in set(val[COL_METHOD].unique())]

    # 結果テーブル作成
    cols = TW_ORDER[:]
    m2tw: Dict[str, Dict[str, float]] = {m: {} for m in ordered_methods}
    for _, row in val.iterrows():
        m = row[COL_METHOD]
        t = row[COL_TW]
        if m in m2tw and t in cols:
            m2tw[m][t] = float(row["val"])
    m2tot: Dict[str, float] = {}
    for _, row in total.iterrows():
        m2tot[row[COL_METHOD]] = float(row["total"])

    # top3判定
    def top3_methods_for_col(colname: str) -> List[str]:
        pairs = []
        for m in ordered_methods:
            v = m2tot.get(m, float("nan")) if colname == "Total" else m2tw[m].get(colname, float("nan"))
            if not pd.isna(v):
                pairs.append((m, v))
        pairs.sort(key=lambda x: x[1], reverse=True)
        return [m for m, _ in pairs[:3]]

    topA = {c: top3_methods_for_col(c) for c in cols + ["Total"]}

    def decorate(m: str, colname: str, s: str) -> str:
        if m not in topA[colname]:
            return s
        rank = topA[colname].index(m)  # 0,1,2
        if rank == 0:
            return r"\uuline{" + s + "}"
        if rank == 1:
            return r"\dashuline{" + s + "}"
        if rank == 2:
            return r"\uline{" + s + "}"
        return s

    # longtable 本文生成
    header = "手法名 & " + " & ".join(cols) + " & Total \\\\"
    lines = []
    lines.append(r"\AppendixTableSetup")
    lines.append(r"\begin{longtable}{l|" + "r"* (len(cols)+1) + "}")
    lines.append(rf"\caption{{{caption}}}\\")
    lines.append(r"\hline")
    lines.append(header)
    lines.append(r"\hline\hline")

    ordered_set = set(ordered_methods)
    for gname, methods in METHOD_GROUPS:
        methods_in = [m for m in methods if m in ordered_set]
        if not methods_in:
            continue
        lines.append(rf"\multicolumn{{{len(cols)+2}}}{{l}}{{\textbf{{{gname}}}}} \\")
        lines.append(r"\hline")
        for m in methods_in:
            row = [sanitize_method_tex(m)]
            for c in cols:
                v = m2tw[m].get(c, float("nan"))
                s = format_value(v)
                s = decorate(m, c, s)
                row.append(s)
            vt = m2tot.get(m, float("nan"))
            st = format_value(vt)
            st = decorate(m, "Total", st)
            row.append(st)
            lines.append(" & ".join(row) + r" \\")
        lines.append(r"\hline")

    lines.append(r"\end{longtable}")
    return "\n".join(lines) + "\n"


def main() -> None:
    csv_path = Path(INPUT_CSV_PATH)
    out_dir = Path(OUTPUT_DIR)
    
    if not csv_path.exists():
        print(f"Error: 入力CSVファイルが見つかりません: {csv_path.resolve()}")
        return

    out_dir.mkdir(parents=True, exist_ok=True)

    # Nのリストは直接使用（除外ロジック削除）
    Ns = TARGET_NS

    print(f"Reading CSV: {csv_path} ...")
    df = pd.read_csv(csv_path)

    # 型変換
    df[COL_N] = df[COL_N].astype(int)
    df[COL_RULE] = df[COL_RULE].astype(str)
    df[COL_UTILITY] = df[COL_UTILITY].astype(str)
    df[COL_TW] = df[COL_TW].astype(str)
    df[COL_METHOD] = df[COL_METHOD].astype(str)

    # 【デバッグ用】CSVに含まれている手法名を確認
    unique_methods_in_csv = df[COL_METHOD].unique()
    print("-" * 20)
    print(f"CSVデータに含まれる手法（Method）の種類数: {len(unique_methods_in_csv)}")
    print(f"CSVデータに含まれる手法名リスト（先頭20件）:\n{unique_methods_in_csv[:20]}")
    print("-" * 20)

    method_order = flatten_method_order(METHOD_GROUPS)
    write_table_style(out_dir)

    include_all_lines: List[str] = []
    include_all_lines.append(r"\input{generated_tables_all/table_style.tex}")

    print(f"Generating tables for N={Ns} ...")
    
    for N in Ns:
        include_n_lines: List[str] = []
        include_n_lines.append(r"\input{generated_tables_all/table_style.tex}")

        n_dir = out_dir / f"n{N}"
        n_dir.mkdir(parents=True, exist_ok=True)

        # 設定された 基準(RULE) x 効用(UTILITY) x 指標(METRIC) でループ
        for rule_key, rule_label in TARGET_RULES:
            for util_key, util_label in TARGET_UTILITIES:
                for metric_key, metric_col, metric_label in TARGET_METRICS:
                    
                    tex = build_longtable_tex(
                        df=df,
                        rule_key=rule_key,
                        rule_label=rule_label,
                        N=N,
                        util_key=util_key,
                        util_label=util_label,
                        metric_col=metric_col,
                        metric_label=metric_label,
                        method_order=method_order,
                    )
                    fname = f"tab_n{N}_{rule_key}_{util_key}_{metric_key}.tex"
                    (n_dir / fname).write_text(tex, encoding="utf-8")

                    input_line = rf"\input{{generated_tables_all/n{N}/{fname}}}"
                    if ONE_TABLE_PER_PAGE:
                        include_n_lines.append(r"\clearpage")
                    include_n_lines.append(input_line)

        (out_dir / f"include_n{N}.tex").write_text("\n".join(include_n_lines) + "\n", encoding="utf-8")
        include_all_lines.append(r"\clearpage")
        include_all_lines.append(rf"\input{{generated_tables_all/include_n{N}.tex}}")

    (out_dir / "include_appendix_allN.tex").write_text("\n".join(include_all_lines) + "\n", encoding="utf-8")

    print("-" * 40)
    print("完了しました。")
    print(f"出力先: {out_dir.resolve()}")
    print("-" * 40)


if __name__ == "__main__":
    main()